### ISSUE TITLE
視窗最大化時不透明

### ISSUE THREAD

**Issue by AlexanderShad** [velade/dynamic-panel#10]
你好。
當我將任何應用程式的視窗擴展到全螢幕時，下拉清單中的透明度消失。
這是應該的嗎？

https://github.com/user-attachments/assets/f391b043-2701-488d-8453-b3e111163262

**Comment by velade** [comment]
這是應該的，透明度我的設計就是和面板保持一致的

**Comment by velade** [comment]
不過我注意到，當你把窗口最大化時，面板位址有變化，但是樣式並未變化（透明度和圓角）。這是你故意修改了代碼嗎？還是從某個版本開始的BUG？
它正常應該是這個樣子的
[Screencast From 2024-09-28 11-36-04.webm](https://github.com/user-attachments/assets/f85c6aff-3c43-4650-88f1-4c1c8ea78c23)

**Comment by AlexanderShad** [comment]
我明白問題出在哪裡了。
您的 Gnome 擴展工作正常。
-blur-my-shell- 和 -dynamic-panel- 的疊加對我有用。
現在我明白了邏輯，抱歉誤導了你


https://github.com/user-attachments/assets/6ded323d-7f85-434d-9e73-81b9a29c126b
