### ISSUE TITLE
擴充功能停止工作

### ISSUE THREAD

**Issue by AlexanderShad** [velade/dynamic-panel#11]
你好。
有時，由於未知原因，擴充功能停止工作，但重新啟動電腦後一切正常。
我可以猜測，在全螢幕查看某些內容時會發生這種情況。例如，一部電影。但這並不確定。
下面是有錯誤的圖片

![Снимок экрана от 2024-09-28 10-44-37](https://github.com/user-attachments/assets/f112c408-4857-49b7-986a-90de6af6f95e)

**Comment by AlexanderShad** [comment]
在計算機進入睡眠狀態後解鎖計算機後也會發生這種情況。

**Comment by AlexanderShad** [comment]
DE: Gnome 46.2

**Comment by velade** [comment]
感謝你的反饋，我已經找到了問題所在，已經修復，請稍後更新
