### ISSUE TITLE
未應用翻譯

### ISSUE THREAD

**Issue by AlexanderShad** [velade/dynamic-panel#12]
由於某種原因，一個短語的翻譯沒有被應用

![Снимок экрана от 2024-09-30 16-45-04](https://github.com/user-attachments/assets/8892e659-a0ae-4f77-9314-b9010905d6b1)

**Comment by velade** [comment]
嗯，因為這個短語我在前面加了空格實現層級縮進的感覺，但翻譯時忘記了加空格，現在我將空格移出了_()。
