### ISSUE TITLE
Windows can pass through the panel

### ISSUE THREAD

**Issue by Limenomen** [velade/dynamic-panel#16]
Hi! Thanks for the awesome extension, it looks amazing! However, there's a small issue. With the following display setup, the panel doesn't stick to the edge as it should, it's as if the trigger is located higher, at the border of the second screen. I hope I explained it clearly :)

The version where the panel works incorrectly.   
![Screenshot from 2024-10-24 23-09-07](https://github.com/user-attachments/assets/b2528613-de81-4cfb-b0b3-ac22a8e457f8)   
With these settings, everything works as expected   
![Screenshot from 2024-10-24 23-09-49](https://github.com/user-attachments/assets/38ab2e06-367d-4f4e-8bfb-179a30ec3fc5)

**Comment by velade** [comment]
I have fixed this bug at version 4.8, You could update later.
