### ISSUE TITLE
bug: 存在圓角的背景

### ISSUE THREAD

**Issue by AlexanderShad** [velade/dynamic-panel#3]
圓角處有背景；它不應該在那裡。請更正

![Снимок экрана от 2024-09-16 20-48-18](https://github.com/user-attachments/assets/ea1ddf6a-ccde-46a0-8887-b58e90554c8f)

**Comment by AlexanderShad** [comment]
OS: ALT Linux
DE: Gnome 46.2
WM: Mutter (Wayland)

**Comment by velade** [comment]
你是否使用了blur my shell或其他更改面板的擴展？在正常情況下panel的結構是雙層的，一個是panel本身，但在其之外有一層panelBox，它默認是透明的，而現在顯然是被什麼其他東西添加了一個背景，這不是我能夠修復的，如果你用了blur my shell，請使用靜態pipeline並記得在pipeline中添加「角落(corner)」層並正確的調整圓角來修復此問題

**Comment by AlexanderShad** [comment]
你好，我明白了，謝謝。
是的，我用 blur my shell

**Comment by AlexanderShad** [comment]
我明白了，問題已經解決了，謝謝。ё
