### ISSUE TITLE
字體顏色可讀性差

### ISSUE THREAD

**Issue by AlexanderShad** [velade/dynamic-panel#6]
你好。
使用淺色主題時，某些字體難以閱讀。
有可能讓它們變暗嗎？
螢幕截圖中的範例

DE Gnome 46.2

![dp1](https://github.com/user-attachments/assets/de7c7e99-dd67-42ac-ab88-a3e74c09614c)
![dp2](https://github.com/user-attachments/assets/de586c36-f3ff-4400-aa39-0bd8dbbe884a)

**Comment by velade** [comment]
請將此問題反饋到 Light Style 擴展下，或其他類似的東西之下，因為這是主題相關的東西，而Gnome自身的淺色主題並不會把這些選單變為白色。
我並沒有修改它。盡管我可以修改，但這超出了這個擴展的負責範圍，並且可能會導致更多的衝突（除非某天我想自行控制主題）。因此需要由「將面板選單變為白色」的東西來解決這個問題。

**Comment by AlexanderShad** [comment]
是的，但是有一個問題，系統是乾淨的。
沒有其他擴充。
這是一個標準主題 Gnome 46.2
OS: ALT Linux


https://github.com/user-attachments/assets/4a1c7319-95a4-4976-9a85-76b7496ec784

**Comment by AlexanderShad** [comment]
在我的個人機器上，有其他擴展，一切看起來都很好:)
作業系統是一樣的。


https://github.com/user-attachments/assets/9cd1892b-f36a-4ede-8570-a8323bf50c86

**Comment by AlexanderShad** [comment]
我會嘗試找出問題所在。
如果我找到了，我會寫信給你

**Comment by velade** [comment]
我不確定是什麼問題，如果我不使用light style擴展，我的機器上gnome似乎並不會對Shell應用淺色主題，它依然是黑色的，包括面板和選單，
![image](https://github.com/user-attachments/assets/d1882529-e135-4d40-9cf6-8120fa1d33ac)
並且由於它不更改文字顏色，所以它會讓我的擴展看起來非常怪異（因為我的擴展把面板改為了白色，但Gnome認為它應該是黑色）
![image](https://github.com/user-attachments/assets/af73ba26-0ad7-4fc4-9353-e5339e4ebe0c)

只有當我打開light style它才正常，而讓Shell支援明亮模式，就是light style存在的唯一意義，因此如果你的系統本身就在更改為淺色模式時會更改panel和panel-menu，那麼其實是不正常的，可能你的系統（ALT Linux）對於gnome有更改，內部集成了light style，就像ubuntu早在gnome 47之前就實現了強調色的調整，並集成在了系統設定中（看起來甚至和gnome47的一樣），但那並不是真正的gnome47之前的標準版本的一部分。你知道，許多的發行版會對桌面環境有一定的修改訂製。

那麼或許你應該反饋到ALT Linux的關於桌面環境的部份。
